services:
  - docker

matrix:
  include:
    - os: linux
      dist: trusty

before_script:
  - docker login --username=$DOCKER_USERNAME --email=DOCKER_PASSWORD https://hub.docker.com

jobs:
  include:
    - stage: latest
      script:
        - docker build -t redwolfgang20/awscli-kubctl:latest .
        - docker tag redwolfgang20/awscli-kubctl:latest redwolfgang20/awscli-kubctl:latest
        - docker push redwolfgang20/awscli-kubctl
